#!/usr/bin/env python3
"""Phase 4 — Section 1: Unit K verification (NO re-runs; persisted artifacts only).

Reads the persisted Unit-K / OU / rolling-baseline CSVs and emits the
verification artifacts under ``reports/phase4/verification/`` plus figures
under ``plots/phase4/verification/``. Nothing here re-runs a strategy or the
Kalman engine; every output traces to a persisted CSV.

Sub-items (Phase-4 instruction Section 1):
  1a reconciliation 20.886 vs 20.914967      -> 1a_reconciliation.csv
  1b full 8-cell table (kalman|frozen|rolling) -> 1b_eight_cell_table.csv
  1c P&L decomposition of kalman best cell    -> 1c_*.csv
  1d "4/4 admissible" denominator             -> 1d_admissible_denominator.csv
  1e reviewer pre-registered predictions      -> 1e_predictions.csv
Figures: h exit-reason stacked, per-trade pnl dist, mu-tracking overlay,
3-engine cost ladder (companion CSVs alongside).
"""

from __future__ import annotations

from pathlib import Path

import matplotlib
import numpy as np
import pandas as pd

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

from apt.backtest import compute_metrics
from apt.phase4 import FIVE_CATEGORY_EXIT_REASONS, canonical_exit_reason, savefig_with_csv

KALMAN = Path("reports/phase3_kalman")
OU = Path("reports/phase3_ou")
OUT = Path("reports/phase4/verification")
FIG = Path("plots/phase4/verification")
BEST_FREQ, BEST_COST = 5, 3  # kalman best cell for 1c

# The matched universe: the 2 pair-folds that survive the OU static-HL gate.
MATCHED = {(4, "INDUSINDBK/HDFCBANK"), (6, "KOTAKBANK/HDFCBANK")}


def _matched_portfolio_metrics(ps: pd.DataFrame) -> dict:
    """Equal-notional portfolio metrics on the matched 2 pair-folds.

    Reaggregates persisted per-session returns (groupby date, mean across
    pairs) and runs ``compute_metrics`` — NOT a strategy re-run.
    """
    ps = ps[ps.apply(lambda r: (r.fold_id, r.pair) in MATCHED, axis=1)]
    port = ps.groupby("date").agg(
        gross_log_ret=("gross_log_ret", "mean"),
        net_log_ret=("net_log_ret", "mean"),
    )
    mg = compute_metrics(port.gross_log_ret.to_numpy())
    mn = compute_metrics(port.net_log_ret.to_numpy())
    return {
        "n_sessions": int(port.shape[0]),
        "gross_total_pct": mg["total_return_pct"],
        "net_total_pct": mn["total_return_pct"],
        "gross_ann_pct": mg["ann_return_pct"],
        "net_ann_pct": mn["ann_return_pct"],
        "gross_sharpe": mg["sharpe"],
        "net_sharpe": mn["sharpe"],
        "net_maxDD_pct": mn["max_drawdown_pct"],
    }


# ----------------------------------------------------------------------
# 1a — reconciliation
# ----------------------------------------------------------------------
def reconcile() -> pd.DataFrame:
    ou = pd.read_csv(OU / "metrics_ou.csv")
    cell = ou[
        (ou.freq_min == 5) & (ou.regime == "B") & (ou.spread_bps == 3) & (ou.stop_mode == "none")
    ]
    c_leg = float(cell.net_ann_pct.iloc[0])  # the official C-leg value
    rows = [
        {
            "value": 20.914967,
            "label": "C-leg (new a*, new (1+beta) billing), frozen-OU 5min/3bps",
            "traces_to": "reports/phase3_ou/metrics_ou.csv row (ou,5,B,3,none) net_ann_pct",
            "persisted_value": c_leg,
            "status": "CANONICAL — matches persisted CSV",
            "note": (
                "metrics_ou.csv is gitignored (regenerated by scripts/15_phase3_ou.py); "
                "the committed anchor is docs/phase3_cost_beta_report.md sec 13.1 "
                "(A=21.241294 / B=20.843599 / C=20.914967). The file does NOT exist as a "
                "tracked blob at 65b15f6 — it is a deterministic working-tree artifact."
            ),
        },
        {
            "value": 20.886,
            "label": "Unit-C chat paste-back 'corrected best-cell net_ann'",
            "traces_to": "NONE — absent from working tree and every git blob (git log -S)",
            "persisted_value": np.nan,
            "status": "UNTRACEABLE — superseded paste-back",
            "note": (
                "Not equal to A/B/C (21.241294 / 20.843599 / 20.914967). Lies between the "
                "billing-only B-leg (20.8436) and the official C-leg (20.9150); most likely an "
                "intermediate paste during Unit C before the A/B/C decomposition was finalized. "
                "Cannot be reproduced from any persisted artifact -> not a number to carry forward."
            ),
        },
    ]
    df = pd.DataFrame(rows)
    df.to_csv(OUT / "1a_reconciliation.csv", index=False)
    print(f"[1a] C-leg persisted net_ann = {c_leg:.6f}  (canonical = 20.914967)")
    print("[1a] 20.886 found in: 0 working-tree files, 0 git blobs -> untraceable paste-back")
    return df


# ----------------------------------------------------------------------
# 1b — full 8-cell table, kalman vs frozen-OU vs rolling_z (matched)
# ----------------------------------------------------------------------
def _trade_counts(path: Path, freq: int, cost: int, extra: dict) -> int:
    t = pd.read_csv(path)
    m = (t.freq_min == freq) & (t.spread_bps == cost)
    for k, v in extra.items():
        m &= t[k] == v
    t = t[m]
    t = t[t.apply(lambda r: (r.fold_id, r.pair) in MATCHED, axis=1)]
    return int(t.shape[0])


def eight_cell_table() -> pd.DataFrame:
    """All three engines on the MATCHED 2 pair-folds, recomputed from the
    persisted per-session returns (self-consistent, full metric set)."""
    ps_k = pd.read_csv(KALMAN / "pair_sessions_kalman.csv")
    ps_o = pd.read_csv(OU / "pair_sessions_ou.csv")
    ps_r = pd.read_csv(OU / "pair_sessions_rolling_baseline.csv")
    rows = []
    for freq in (5, 15):
        for cost in (1, 3, 5, 8):
            k = _matched_portfolio_metrics(
                ps_k[(ps_k.freq_min == freq) & (ps_k.regime == "B") & (ps_k.spread_bps == cost)]
            )
            o = _matched_portfolio_metrics(
                ps_o[
                    (ps_o.freq_min == freq)
                    & (ps_o.regime == "B")
                    & (ps_o.spread_bps == cost)
                    & (ps_o.stop_mode == "none")
                ]
            )
            r = _matched_portfolio_metrics(
                ps_r[(ps_r.freq_min == freq) & (ps_r.regime == "B") & (ps_r.spread_bps == cost)]
            )
            row = {"freq_min": freq, "cost_bps": cost}
            row.update(
                {
                    "k_n_trades": _trade_counts(KALMAN / "trades_kalman.csv", freq, cost, {}),
                    "ou_n_trades": _trade_counts(
                        OU / "trades_ou.csv", freq, cost, {"regime": "B", "stop_mode": "none"}
                    ),
                    "rz_n_trades": _trade_counts(
                        OU / "trades_rolling_baseline.csv", freq, cost, {"regime": "B"}
                    ),
                }
            )
            for pre, m in (("k", k), ("ou", o), ("rz", r)):
                row[f"{pre}_gross_total_pct"] = m["gross_total_pct"]
                row[f"{pre}_net_total_pct"] = m["net_total_pct"]
                row[f"{pre}_gross_sharpe"] = m["gross_sharpe"]
                row[f"{pre}_net_sharpe"] = m["net_sharpe"]
                row[f"{pre}_net_ann_pct"] = m["net_ann_pct"]
                row[f"{pre}_net_maxDD_pct"] = m["net_maxDD_pct"]
            rows.append(row)
    df = pd.DataFrame(rows)
    df.to_csv(OUT / "1b_eight_cell_table.csv", index=False)

    # cross-check vs persisted matched_metrics.csv (OU + rolling_z net%)
    mm = pd.read_csv(OU / "figures/matched_universe/matched_metrics.csv")
    chk = []
    for _, mrow in mm.iterrows():
        pre = {"ou": "ou", "rolling_z": "rz"}.get(mrow.engine)
        if pre is None:
            continue
        ours = df[(df.freq_min == mrow.freq_min) & (df.cost_bps == mrow.spread_bps)]
        if ours.empty:
            continue
        chk.append(abs(float(ours[f"{pre}_net_total_pct"].iloc[0]) - mrow.net_total_pct))
    print(f"[1b] matched cross-check vs matched_metrics.csv: max |Δnet%| = {max(chk):.4f}")
    print(f"[1b] wrote full 8-cell table: {df.shape[0]} cells x kalman/frozen/rolling (matched)")
    return df


# ----------------------------------------------------------------------
# helpers to load best-cell trades
# ----------------------------------------------------------------------
def _kalman_best_trades() -> pd.DataFrame:
    t = pd.read_csv(KALMAN / "trades_kalman.csv")
    t = t[(t.freq_min == BEST_FREQ) & (t.spread_bps == BEST_COST)].copy()
    t["exit_canon"] = t.exit_reason.map(canonical_exit_reason)
    return t


def _frozen_best_trades() -> pd.DataFrame:
    t = pd.read_csv(OU / "trades_ou.csv")
    t = t[
        (t.freq_min == BEST_FREQ)
        & (t.regime == "B")
        & (t.spread_bps == BEST_COST)
        & (t.stop_mode == "none")
    ].copy()
    t["exit_canon"] = t.exit_reason.map(canonical_exit_reason)
    return t


# ----------------------------------------------------------------------
# 1c(a) — exit-reason mix + share of net per reason (kalman vs frozen)
# ----------------------------------------------------------------------
def exit_reason_mix(kt: pd.DataFrame, ft: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for name, t in (("kalman", kt), ("frozen_ou", ft)):
        tot_net = t.net_log_pnl.sum()
        for reason in FIVE_CATEGORY_EXIT_REASONS + ("__OTHER__",):
            sub = t[t.exit_canon == reason]
            if sub.empty and reason == "__OTHER__":
                continue
            rows.append(
                {
                    "engine": name,
                    "exit_reason": reason,
                    "n_trades": int(sub.shape[0]),
                    "share_of_trades": sub.shape[0] / max(t.shape[0], 1),
                    "net_log_pnl_sum": sub.net_log_pnl.sum(),
                    "share_of_net": (sub.net_log_pnl.sum() / tot_net) if tot_net != 0 else np.nan,
                }
            )
    df = pd.DataFrame(rows)
    df.to_csv(OUT / "1c_a_exit_reason_mix.csv", index=False)
    return df


# ----------------------------------------------------------------------
# 1c(b) — per-trade net P&L distribution (kalman vs frozen)
# ----------------------------------------------------------------------
def per_trade_dist(kt: pd.DataFrame, ft: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for name, t in (("kalman", kt), ("frozen_ou", ft)):
        v = t.net_log_pnl.to_numpy()
        g = t.gross_log_pnl.to_numpy()
        rows.append(
            {
                "engine": name,
                "n_trades": int(v.size),
                "net_mean_bps": float(np.mean(v) * 1e4),
                "net_median_bps": float(np.median(v) * 1e4),
                "net_p5_bps": float(np.percentile(v, 5) * 1e4),
                "net_p95_bps": float(np.percentile(v, 95) * 1e4),
                "net_worst_bps": float(np.min(v) * 1e4),
                "gross_mean_bps": float(np.mean(g) * 1e4),
                "win_rate_net": float(np.mean(v > 0)),
            }
        )
    df = pd.DataFrame(rows)
    df.to_csv(OUT / "1c_b_per_trade_dist.csv", index=False)
    return df


# ----------------------------------------------------------------------
# 1c(c) — overlap: fraction of kalman gross accrued in windows where the
# frozen arm held a losing time_stop/fold_close position (same pair-fold)
# ----------------------------------------------------------------------
def overlap_fraction(ft: pd.DataFrame) -> pd.DataFrame:
    ps = pd.read_csv(KALMAN / "pair_sessions_kalman.csv")
    ps = ps[(ps.freq_min == BEST_FREQ) & (ps.spread_bps == BEST_COST)].copy()
    ps["date"] = pd.to_datetime(ps.date).dt.date

    # frozen losing time_stop / fold_close windows, per pair-fold
    loser = ft[(ft.exit_canon.isin(["time_stop", "fold_close"])) & (ft.net_log_pnl < 0)].copy()
    loser["entry_d"] = pd.to_datetime(loser.entry_ts).dt.date
    loser["exit_d"] = pd.to_datetime(loser.exit_ts).dt.date

    rows = []
    total_gross = ps.gross_log_ret.sum()
    in_window_gross = 0.0
    for (fid, pair), grp in ps.groupby(["fold_id", "pair"]):
        wins = loser[(loser.fold_id == fid) & (loser.pair == pair)]
        mask = pd.Series(False, index=grp.index)
        for _, w in wins.iterrows():
            mask |= (grp.date >= w.entry_d) & (grp.date <= w.exit_d)
        g_in = grp.loc[mask, "gross_log_ret"].sum()
        g_all = grp.gross_log_ret.sum()
        in_window_gross += g_in
        rows.append(
            {
                "fold_id": fid,
                "pair": pair,
                "n_frozen_losing_timestop_foldclose": int(wins.shape[0]),
                "kalman_gross_in_window": g_in,
                "kalman_gross_total_pairfold": g_all,
                "fraction_in_window": (g_in / g_all) if g_all != 0 else np.nan,
            }
        )
    rows.append(
        {
            "fold_id": "ALL",
            "pair": "ALL",
            "n_frozen_losing_timestop_foldclose": int(loser.shape[0]),
            "kalman_gross_in_window": in_window_gross,
            "kalman_gross_total_pairfold": total_gross,
            "fraction_in_window": (in_window_gross / total_gross) if total_gross != 0 else np.nan,
        }
    )
    df = pd.DataFrame(rows)
    df.to_csv(OUT / "1c_c_overlap.csv", index=False)
    return df


# ----------------------------------------------------------------------
# 1c(d) — mu_t tracking: total |Delta mu| in sigma_eq units + profit-
# truncation-by-tracking (only INDUSINDBK fold4 overlay is persisted +
# traded; KOTAK overlay was NOT persisted -> [TODO data]).
# ----------------------------------------------------------------------
def mu_tracking(kt: pd.DataFrame) -> pd.DataFrame:
    rows = []
    # INDUSINDBK fold4 f5 — traded survivor with persisted overlay
    ov_path = KALMAN / "mu_overlay_INDUSINDBK_HDFCBANK_fold4_f5.csv"
    ov = pd.read_csv(ov_path)
    ov["ts"] = pd.to_datetime(ov.ts)
    pf_trades = kt[(kt.fold_id == 4) & (kt.pair == "INDUSINDBK/HDFCBANK")].copy()
    pf_trades["entry_ts"] = pd.to_datetime(pf_trades.entry_ts)
    pf_trades["exit_ts"] = pd.to_datetime(pf_trades.exit_ts)

    # recover sigma_eq_resid from the entry identity z = (spread - mu)/sigma_eq
    sig_est = []
    for _, tr in pf_trades.iterrows():
        m = ov[ov.ts == tr.entry_ts]
        if not m.empty and tr.z_entry != 0:
            sig_est.append((m.spread.iloc[0] - m.mu_kalman.iloc[0]) / tr.z_entry)
    sigma_eq_resid = float(np.median(sig_est)) if sig_est else np.nan

    # per-session mu path -> total |Delta mu|
    ov["date"] = ov.ts.dt.date
    sess_mu = ov.groupby("date").mu_kalman.first()
    total_abs_dmu = float(np.abs(np.diff(sess_mu.to_numpy())).sum())
    total_abs_dmu_sigeq = total_abs_dmu / sigma_eq_resid if sigma_eq_resid else np.nan

    # profit-truncation: did mu move TOWARD the entry spread during holding?
    n_trunc, n_tot = 0, 0
    for _, tr in pf_trades.iterrows():
        me = ov[ov.ts == tr.entry_ts]
        mx = ov[ov.ts == tr.exit_ts]
        if me.empty or mx.empty:
            continue
        n_tot += 1
        mu0, mu1 = me.mu_kalman.iloc[0], mx.mu_kalman.iloc[0]
        entry_spread = me.spread.iloc[0]
        # mu moved toward entry spread if |mu1 - entry_spread| < |mu0 - entry_spread|
        if abs(mu1 - entry_spread) < abs(mu0 - entry_spread):
            n_trunc += 1
    rows.append(
        {
            "fold_id": 4,
            "pair": "INDUSINDBK/HDFCBANK",
            "freq_min": 5,
            "traded": True,
            "sigma_eq_resid_recovered": sigma_eq_resid,
            "total_abs_dmu_log": total_abs_dmu,
            "total_abs_dmu_sigma_eq": total_abs_dmu_sigeq,
            "n_trades": n_tot,
            "n_trades_anchor_moved_toward_entry": n_trunc,
            "frac_trunc": (n_trunc / n_tot) if n_tot else np.nan,
        }
    )

    # fold6 INDUSINDBK (diagnostic, NOT traded) — overlay persisted but no
    # trades -> report total |Delta mu| in log units; sigma_eq + truncation
    # are [TODO data] (no trades to recover sigma_eq from; KOTAK overlay
    # was never persisted by the Unit-K run).
    ov6 = pd.read_csv(KALMAN / "mu_overlay_INDUSINDBK_HDFCBANK_fold6_f5.csv")
    ov6["date"] = pd.to_datetime(ov6.ts).dt.date
    sess_mu6 = ov6.groupby("date").mu_kalman.first()
    rows.append(
        {
            "fold_id": 6,
            "pair": "INDUSINDBK/HDFCBANK",
            "freq_min": 5,
            "traded": False,
            "sigma_eq_resid_recovered": np.nan,  # [TODO data] no trades
            "total_abs_dmu_log": float(np.abs(np.diff(sess_mu6.to_numpy())).sum()),
            "total_abs_dmu_sigma_eq": np.nan,  # [TODO data]
            "n_trades": 0,
            "n_trades_anchor_moved_toward_entry": 0,
            "frac_trunc": np.nan,
        }
    )
    rows.append(
        {
            "fold_id": 6,
            "pair": "KOTAKBANK/HDFCBANK",
            "freq_min": 5,
            "traded": True,
            "sigma_eq_resid_recovered": np.nan,  # [TODO data] overlay not persisted
            "total_abs_dmu_log": np.nan,
            "total_abs_dmu_sigma_eq": np.nan,
            "n_trades": int(kt[(kt.fold_id == 6) & (kt.pair == "KOTAKBANK/HDFCBANK")].shape[0]),
            "n_trades_anchor_moved_toward_entry": -1,  # sentinel: not computable
            "frac_trunc": np.nan,
        }
    )
    df = pd.DataFrame(rows)
    df.to_csv(OUT / "1c_d_mu_tracking.csv", index=False)
    return df, sigma_eq_resid, ov, pf_trades


# ----------------------------------------------------------------------
# 1d — "4/4 admissible" denominator
# ----------------------------------------------------------------------
def admissible_denominator() -> pd.DataFrame:
    st = pd.read_csv(KALMAN / "selection_table.csv")
    ss = pd.read_csv(KALMAN / "selection_summary.csv")
    # denominator = distinct (fold_id, pair, freq) survivor rows at any H
    keys = st[["fold_id", "pair", "freq_min"]].drop_duplicates()
    n_pairfolds = st[["fold_id", "pair"]].drop_duplicates().shape[0]
    n_freqs = st.freq_min.nunique()
    df = pd.DataFrame(
        [
            {
                "denominator_meaning": "distinct (pair-fold x freq) survivor units scored per H",
                "n_pairfold_x_freq": int(keys.shape[0]),
                "n_distinct_pairfolds": int(n_pairfolds),
                "n_freqs": int(n_freqs),
                "decomposition": f"{n_pairfolds} pair-folds x {n_freqs} freqs = {keys.shape[0]}",
                "n_total_in_summary_chosen_H": int(ss[ss.chosen].n_total.iloc[0]),
                "n_admissible_chosen_H": int(ss[ss.chosen].n_admissible.iloc[0]),
            }
        ]
    )
    df.to_csv(OUT / "1d_admissible_denominator.csv", index=False)
    return df


# ----------------------------------------------------------------------
# 1e — reviewer pre-registered predictions
# ----------------------------------------------------------------------
def predictions(kt: pd.DataFrame, mix: pd.DataFrame, overlap: pd.DataFrame) -> pd.DataFrame:
    km = pd.read_csv(KALMAN / "metrics_kalman.csv")
    ou = pd.read_csv(OU / "metrics_ou.csv")
    kbest = km[(km.freq_min == BEST_FREQ) & (km.spread_bps == BEST_COST)].iloc[0]
    obest = ou[
        (ou.freq_min == BEST_FREQ)
        & (ou.regime == "B")
        & (ou.spread_bps == BEST_COST)
        & (ou.stop_mode == "none")
    ].iloc[0]

    mr_share = mix[
        (mix.engine == "kalman") & (mix.exit_reason == "mean_revert")
    ].share_of_trades.iloc[0]
    avg_capture_bps = float(kt.gross_log_pnl.mean() * 1e4)
    overlap_all = overlap[overlap.fold_id == "ALL"].fraction_in_window.iloc[0]
    k_maxdd = float(kbest.net_max_drawdown_pct)
    o_maxdd = float(obest.net_max_drawdown_pct)

    rows = [
        {
            "prediction": ">=80% mean_revert exits (best cell)",
            "metric": mr_share,
            "threshold": 0.80,
            "verdict": "MET" if mr_share >= 0.80 else "NOT MET",
        },
        {
            "prediction": "avg gross capture 200-260 bps/trade",
            "metric": avg_capture_bps,
            "threshold": "[200,260]",
            "verdict": "MET" if 200 <= avg_capture_bps <= 260 else "NOT MET",
        },
        {
            "prediction": "majority of kalman gross in frozen losing time_stop/fold_close windows",
            "metric": overlap_all,
            "threshold": 0.50,
            "verdict": "MET" if overlap_all > 0.50 else "NOT MET",
        },
        {
            "prediction": "kalman max_DD better than frozen -22%",
            "metric": k_maxdd,
            "threshold": o_maxdd,
            "verdict": "MET" if k_maxdd > o_maxdd else "NOT MET",
        },
    ]
    df = pd.DataFrame(rows)
    df.to_csv(OUT / "1e_predictions.csv", index=False)
    return df


# ----------------------------------------------------------------------
# Figures
# ----------------------------------------------------------------------
def fig_exit_stacked(mix: pd.DataFrame) -> None:
    piv = mix.pivot_table(index="engine", columns="exit_reason", values="n_trades", fill_value=0)
    cats = [c for c in FIVE_CATEGORY_EXIT_REASONS if c in piv.columns]
    fig, ax = plt.subplots(figsize=(7, 4))
    bottom = np.zeros(len(piv))
    for c in cats:
        ax.bar(piv.index, piv[c], bottom=bottom, label=c)
        bottom += piv[c].to_numpy()
    ax.set_ylabel("n_trades")
    ax.set_title("h: exit-reason mix — kalman_mu vs frozen-OU (5min / B / 3bps)")
    ax.legend(fontsize=8)
    savefig_with_csv(fig, FIG / "h_exit_reason_stacked.png", mix)
    plt.close(fig)


def fig_pnl_dist(kt: pd.DataFrame, ft: pd.DataFrame) -> None:
    fig, ax = plt.subplots(figsize=(7, 4))
    bins = np.linspace(-0.05, 0.12, 40)
    ax.hist(kt.net_log_pnl, bins=bins, alpha=0.6, label=f"kalman (n={kt.shape[0]})")
    ax.hist(ft.net_log_pnl, bins=bins, alpha=0.6, label=f"frozen (n={ft.shape[0]})")
    ax.axvline(0, color="k", lw=0.8)
    ax.set_xlabel("net log P&L per trade")
    ax.set_title("per-trade net P&L — kalman vs frozen (5min / B / 3bps)")
    ax.legend()
    data = pd.concat(
        [
            kt[["net_log_pnl"]].assign(engine="kalman"),
            ft[["net_log_pnl"]].assign(engine="frozen_ou"),
        ]
    )
    savefig_with_csv(fig, FIG / "per_trade_pnl_dist.png", data)
    plt.close(fig)


def fig_mu_tracking(ov: pd.DataFrame, pf_trades: pd.DataFrame, sigma_eq: float) -> None:
    fig, ax = plt.subplots(figsize=(9, 4))
    ax.plot(ov.ts, ov.spread, color="0.5", lw=0.5, label="spread")
    ax.plot(ov.ts, ov.mu_kalman, color="C1", lw=1.2, label="mu_kalman (H=20)")
    ax.plot(ov.ts, ov.mu_frozen, color="C0", lw=1.0, ls="--", label="mu_frozen")
    for _, tr in pf_trades.iterrows():
        ax.axvline(pd.to_datetime(tr.entry_ts), color="g", lw=0.4, alpha=0.4)
        ax.axvline(pd.to_datetime(tr.exit_ts), color="r", lw=0.4, alpha=0.4)
    ax.set_title(f"mu-tracking INDUSINDBK/HDFCBANK fold4 f5  (sigma_eq_resid={sigma_eq:.5f})")
    ax.legend(fontsize=8)
    savefig_with_csv(
        fig,
        FIG / "mu_tracking_indusindbk_fold4.png",
        ov[["ts", "spread", "mu_frozen", "mu_kalman"]],
    )
    plt.close(fig)


def fig_cost_ladder(tbl: pd.DataFrame) -> None:
    fig, axes = plt.subplots(1, 2, figsize=(12, 4))
    for ax, freq in zip(axes, (5, 15), strict=True):
        sub = tbl[tbl.freq_min == freq].sort_values("cost_bps")
        ax.plot(sub.cost_bps, sub.k_net_sharpe, "o-", label="kalman")
        ax.plot(sub.cost_bps, sub.ou_net_sharpe, "s-", label="frozen-OU")
        ax.plot(sub.cost_bps, sub.rz_net_sharpe, "^-", label="rolling_z")
        ax.set_title(f"net Sharpe vs cost — f{freq} / B")
        ax.set_xlabel("cost (bps)")
        ax.set_ylabel("net Sharpe")
        ax.legend(fontsize=8)
    savefig_with_csv(fig, FIG / "d_cost_ladder_3engine.png", tbl)
    plt.close(fig)


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    FIG.mkdir(parents=True, exist_ok=True)

    reconcile()
    tbl = eight_cell_table()
    kt = _kalman_best_trades()
    ft = _frozen_best_trades()
    mix = exit_reason_mix(kt, ft)
    dist = per_trade_dist(kt, ft)
    overlap = overlap_fraction(ft)
    mu_df, sigma_eq, ov, pf_trades = mu_tracking(kt)
    den = admissible_denominator()
    preds = predictions(kt, mix, overlap)

    fig_exit_stacked(mix)
    fig_pnl_dist(kt, ft)
    fig_mu_tracking(ov, pf_trades, sigma_eq)
    fig_cost_ladder(tbl)

    print("\n=== 1c(a) exit-reason mix ===")
    print(mix.to_string(index=False))
    print("\n=== 1c(b) per-trade distribution ===")
    print(dist.to_string(index=False))
    print("\n=== 1c(c) overlap ===")
    print(overlap.to_string(index=False))
    print("\n=== 1c(d) mu tracking ===")
    print(mu_df.to_string(index=False))
    print("\n=== 1d denominator ===")
    print(den.to_string(index=False))
    print("\n=== 1e predictions ===")
    print(preds.to_string(index=False))
    print("\n=== s1_unit_k_verification complete ===")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
